spring.application.name=SEP490_SmartRobot

#spring.datasource.url=jdbc:mysql://localhost:3306/robot2
#spring.datasource.username=root
#spring.datasource.password=123456
spring.datasource.url=jdbc:mysql://trolley.proxy.rlwy.net:43935/railway
spring.datasource.username=root
spring.datasource.password=GPDarChAxYFVbfTGgMuvTPhUptLoxMDD
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto = update

spring.main.allow-circular-references=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=0923040196h@gmail.com
spring.mail.password=bvzhzchemutgalxo

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Thymeleaf template configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.mail.default-encoding=UTF-8

vnpay.tmnCode=JMOMGVWU
vnpay.hashSecret=ZXU2DBOGI2G1KT99UQVY6PL8AHL6YW0V
vnpay.paymentUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

springdoc.swagger-ui.path=/swagger

robot.flask.url=http://localhost:5000

#payos.client-id=7c75f8df-95ea-4f04-b538-213b0f68072f
#payos.api-key=214554c1-5b17-44b7-9e73-b1b322cb3265
#payos.checksum-key=c7ce13e842d863259318b070d7bf423966264aa539df7906eb4c7f541d122d7d
#payos.endpoint=https://api-merchant.payos.vn/v2/payment-requests

payos.client-id=${PAYOS_CLIENT_ID}
payos.api-key=${PAYOS_API_KEY}
payos.checksum-key=${PAYOS_CHECKSUM_KEY}
payos.endpoint=${PAYOS_ENDPOINT}
